package constants

const (
	ENV_UPDATE_CRON    = "RAITO_CLI_UPDATE_CRON"
	ENV_STDOUT_FILE    = "RAITO_CLI_CONTAINER_STDOUT_FILE"
	ENV_STDERR_FILE    = "RAITO_CLI_CONTAINER_STDERR_FILE"
	ENV_LIVENESS_FILE  = "RAITO_CLI_CONTAINER_LIVENESS_FILE"
	ENV_READINESS_FILE = "RAITO_CLI_CONTAINER_READINESS_FILE"
)
