linters-settings:
  #check:
    #check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow # not important for now
      - unnamedResult # not important
      - hugeParam #to be checked
      - commentFormatting
      - paramTypeCombine

  govet:
    check-shadowing: true

  revive:
    rules:
      - name: exported
        disabled: true

  wsl:
    allow-assign-and-anything: true
    allow-cuddle-declarations: true # should be false

  nolintlint:
    allow-no-explanation: [ ]
    require-explanation: false
    require-specific: false

  gosec:
    excludes:
      - G404 # To be checked: Insecure random number source (rand)

  predeclared:
    ignore: "error"

  gomnd:
    ignored-functions:
      - 'math.*' # Magic number generation, should be fixed and removed?

  stylecheck:
    checks:
      - all
      - '-ST1003'

linters:
  disable-all: true
  enable:
    - bodyclose
    #- deadcode #The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.
    #- depguard #We should create a correct config to enabe depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    #- goimports #Issues with new version of goimports. Not able to parse issues
    #- gomnd # Magic numbers should be fixed and enable gomnd,
    - gocyclo
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    #- structcheck #The owner seems to have abandoned the linter.
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
   # - wrapcheck # 3th party errors should be wrapped to not lose context
    - wsl

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - cdk/
    - lambda/appserver/graphql/generated/generated.go
    - global/testing/*
  skip-files:
    - '(.+)wire_gen\.go'
  skip-dirs-use-default: true
  modules-download-mode: readonly

output:
  path-prefix: ""
  sort-results: true
  format: github-actions
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false