name: Raito CLI - Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_SECRETS_TOKEN_USER }}
          password: ${{ secrets.CI_SECRETS_TOKEN }}

      - name: Docker meta for deploy
        id: meta-deploy
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/raito-io/raito-cli-runner
          flavor: latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.description=RAITO CLI runner
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.vendor=Raito
            org.opencontainers.image.documentation=https://docs.raito.io/
            org.opencontainers.image.source=https://github.com/raito-io/cli-runner

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: deploy
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ steps.meta-deploy.outputs.tags }}
          labels: ${{ steps.meta-deploy.outputs.labels }}
          provenance: false

      - name: Docker meta for amazon
        id: meta-amazon
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/raito-io/raito-cli-runner
          flavor: |
            latest=auto
            suffix=-amazon,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.description=RAITO CLI runner
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.vendor=Raito
            org.opencontainers.image.documentation=https://docs.raito.io/
            org.opencontainers.image.source=https://github.com/raito-io/cli-runner

      - name: Build and push amazon
        uses: docker/build-push-action@v5
        with:
          context: .
          target: amazonlinux
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-amazon.outputs.tags }}
          labels: ${{ steps.meta-amazon.outputs.labels }}
          provenance: false

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_DEPLOY_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ECR_REGISTRY_ID }}
          registry-type: "private"

      - name: Docker meta for amazon marketplace
        id: meta-amazon-marketplace
        uses: docker/metadata-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          images: |
            ${{ env.ECR_REGISTRY}}/raito/raito-cli
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.description=RAITO CLI runner
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.vendor=Raito
            org.opencontainers.image.documentation=https://docs.raito.io/
            org.opencontainers.image.source=https://github.com/raito-io/cli-runner

      - name: Build and push amazon marketplace
        uses: docker/build-push-action@v5
        with:
          context: .
          target: amazonlinux
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-amazon-marketplace.outputs.tags }}
          labels: ${{ steps.meta-amazon-marketplace.outputs.labels }}
          provenance: false

      - name: Get AWS Marketplace details
        run: |
          aws marketplace-catalog describe-entity --catalog "AWSMarketplace" --entity-id "${{ secrets.AWS_MARKETPLACE_PRODUCT_ID}}" --query 'Details' | jq 'fromjson';

      - name: Add new version to AWS Marketplace
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION: ${{ steps.meta-amazon-marketplace.outputs.version}}

        run: |
          DETAILS_JSON='{
            "Version": {
              "VersionTitle": "Raito CLI Runner ${{ env.VERSION }}",
              "ReleaseNotes": "Raito CLI Runner ${{ env.VERSION }}. Please check https://github.com/raito-io/cli-runner for more information"
            },
            "DeliveryOptions": [
              {
                "DeliveryOptionTitle": "Raito CLI Runner - Docker",
                "Details": {
                  "EcrDeliveryOptionDetails": {
                    "ContainerImages": [
                      "${{ env.ECR_REGISTRY}}/raito/raito-cli:${{ env.VERSION}}"
                    ],
                    "CompatibleServices": [
                      "ECS", "EKS"
                    ],
                    "Description": "Docker container for the Raito CLI Runner.",
                    "UsageInstructions": "Installation instructions can be found on http://docs.raito.io/docs/cli/installation/docker."
                  }
                }
              }
            ]
          }';

          DETAILS_JSON_STRING="$(echo "${DETAILS_JSON}" | jq 'tostring';)";

          aws marketplace-catalog start-change-set \
          --catalog "AWSMarketplace" \
          --change-set '[
            {
              "ChangeType": "AddDeliveryOptions",
              "Entity": {
                "Identifier": "'"${{ secrets.AWS_MARKETPLACE_PRODUCT_ID}}"'",
                "Type": "ContainerProduct@1.0"
              },
              "Details": '"${DETAILS_JSON_STRING}"'
            }
          ]';
